### ISSUE TITLE
Support for fasthttp

### ISSUE THREAD

**Issue by codecat** [henvic/httpretty#28]
It would be great if this supported [fasthttp](https://github.com/valyala/fasthttp) as well. That way we can use it with frameworks such as [Fiber](https://gofiber.io/).

**Comment by henvic** [comment]
Sorry, but I've no interest in adding or maintaining support or compatibility with fasthttp.
It'd be too much of a hassle to do so, but the main reason why I don't plan to do so is because [fasthttp](https://www.reddit.com/r/golang/comments/ghkboz/whats_wrong_with_fasthttp/) doesn't implement the HTTP protocol properly and is very problematic.

Also, I think it's worth to mention that the main problem fasthttp tries to solve (performance at the router-level) is generally not where the bottleneck of an application lies, and I believe most people using it doesn't take advantage of its purposed advantages.

**Comment by codecat** [comment]
I read the Reddit thread you linked and I guess the big problem with it is mostly the Go API differences that makes it incompatible with the Go http API.

Unfortunate, but understandable. Thanks for answering 😊

**Comment by henvic** [comment]
You're welcome!
